# Generated by Django 3.2.5 on 2021-07-05 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0001_initial'),
        ('book', '0002_alter_book_author_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField()),
                ('title', models.CharField(max_length=100)),
                ('written_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='book.book')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='movie.movie')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replied', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replied', to='post.post')),
                ('replying', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replying', to='post.post')),
            ],
            options={
                'unique_together': {('replied', 'replying')},
            },
        ),
    ]
