# Generated by Django 3.2.5 on 2021-07-06 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='replying_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='post.post'),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
