# Generated by Django 3.2.5 on 2021-07-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(related_name='films', to='movie.Director'),
        ),
        migrations.DeleteModel(
            name='Movie_Director',
        ),
    ]
