# Generated by Django 3.2.5 on 2021-07-07 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_movie_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
