# Generated by Django 3.2.5 on 2021-07-07 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20210707_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='title_en',
            new_name='title_original',
        ),
        migrations.AddField(
            model_name='movie',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
