# Generated by Django 3.2.5 on 2021-07-08 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_alter_movie_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['rating']},
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='poster_path',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='popularity',
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='films', to='movie.Actor'),
        ),
    ]
