# Generated by Django 3.2.5 on 2021-07-08 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_auto_20210708_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-rating']},
        ),
    ]
