# Generated by Django 3.2.5 on 2021-07-05 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book_author',
            unique_together={('book', 'author')},
        ),
    ]
