# Generated by Django 3.2.5 on 2021-07-06 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_author_unique_together'),
        ('movie', '0001_initial'),
        ('post', '0002_alter_post_writer'),
        ('comment', '0001_initial'),
        ('user', '0004_auto_20210706_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_books',
            field=models.ManyToManyField(related_name='favorings', to='book.Book'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_movies',
            field=models.ManyToManyField(related_name='favorings', to='movie.Movie'),
        ),
        migrations.AddField(
            model_name='user',
            name='like_comments',
            field=models.ManyToManyField(related_name='likers', to='comment.Comment'),
        ),
        migrations.AddField(
            model_name='user',
            name='like_posts',
            field=models.ManyToManyField(related_name='likers', to='post.Post'),
        ),
    ]
