# Generated by Django 3.2.5 on 2021-07-06 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210706_1029'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like_comment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='like_comment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='like_comment',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='like_post',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='like_post',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like_post',
            name='user',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='Like_Comment',
        ),
        migrations.DeleteModel(
            name='Like_Post',
        ),
    ]
